config/routes.rb
Rails.application.routes.draw do

  # Authentication, Authorization
  devise_for :users

  # Forum
  mount SimpleDiscussion::Engine => "/forum"

  # Pages
  root to: 'pages#home'
  get '/info', to: 'pages#info', as: 'info'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  # Training
  resources :smell_programs, only: [:show, :index, :new, :create] do
    resources :smell_entries, only: [:new, :create] do
      collection do
        get :countdown
      end
    end
  end

  # Shop
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  resources :products, only: [:index, :show]
  resources :orders, only: [:index, :create] do
    resources :payments, only: :new
    member do
      get :success
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert" id="devise-info">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert" id="devise-warning">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="container text-center">
      <ul>
        <a href="#"><i class="fab fa-facebook-f mx-2"></i></a>
        <a href="#"><i class="fab fa-twitter mx-2"></i></a>
        <a href="#"><i class="fab fa-instagram mx-2"></i></a>
      </ul>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light w-100 mr-5 mb-1">
  <!-- <div class="navbar-btn"> </div> -->

  <div class="navbar-title">
    <h3 class="text-dark m-0 p-0"><%= @navbar_title %></h3>
  </div>

  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> -->
  <button class="navbar-btn navbar-toggler"  id="navbarDropdown" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <%= link_to "Home", root_path, class: "dropdown-item" %>
    <% if user_signed_in? %>
      <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
      <%= link_to "Forum", simple_discussion_path, class: "dropdown-item"  %>
    <% end %>

    <%#= link_to "Profile", profile_path, class: "dropdown-item" %>
    <% if user_signed_in? %>
      <%= link_to "Shop", products_path, class: "dropdown-item" %>
      <%= link_to "Order History", orders_path, class: "dropdown-item" %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete,  class: "dropdown-item" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
      <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
    <% end %>
    <%= link_to "About", info_path, class: "dropdown-item" %>
  </div>
</div>

<% if @navbar_title.present? %>
   <hr>
<% end %>

app/views/shared/_section_header.html.erb
<div class="container">
  <div class="section-container">
    <p class="section-category section-positioning">TRAINING</p>
    <h1 class="section-title">Uncovered scent</h1>
  </div>
</div>

app/views/shared/_spacer.html.erb
<hr/>