config/routes.rb
Rails.application.routes.draw do

  # Authentication, Authorization
  devise_for :users

  # Forum
  mount SimpleDiscussion::Engine => "/forum"

  # Pages
  root to: 'pages#home'
  get '/info', to: 'pages#info', as: 'info'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  # Training
  resources :smell_programs, only: [:show, :index, :new, :create] do
    resources :smell_entries, only: [:new, :create] do
      collection do
        get :countdown
      end
    end
  end

  # Shop
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  resources :products, only: [:index, :show]
  resources :orders, only: [:index, :create] do
    resources :payments, only: :new
    member do
      get :success
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product

  monetize :amount_cents
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders.order("created_at DESC")
  end

  def create
    product = Product.find(params[:product_id])
    order  = Order.create!(product: product, product_sku: product.sku, amount: product.price, state: 'pending', user: current_user)

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: product.name,
        images: [product.photo.url],
        amount: product.price_cents,
        currency: 'eur',
        quantity: 1
      }],
      success_url: "http://www.anosmiatherapy.com/order/#{order.id}/success?session_id={CHECKOUT_SESSION_ID}",
      cancel_url: "http://www.anosmiatherapy.com/order/#{order.id}/cancel?session_id={CHECKOUT_SESSION_ID}"
    )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)
  end

  def success
    session = Stripe::Checkout::Session.retrieve(params[:session_id])
    customer = Stripe::Customer.retrieve(session.customer)
    @order = current_user.orders.find(params[:id])
  end
end

app/views/orders/index.html.erb
<div class="container">
  <p class="section-category" id="sec-order-title">ORDERS</p>
  <h2 id="shop-header">History</h2>
  <div class="shop-cards">
    <% @orders.each do |order| %>
      <div class="order-card">
        <%#= cl_image_tag order.product.photo.key %>
        <%= link_to order_path(order) do %>
        <%= cl_image_tag order.product.photo.key, crop: :fill, class: "order-img" %>
      <% end %>
        <div class="li-order-history">
          <h4 class="order-id">Order #<%= order.id %></h4>
          <p class="order-date">Order Date: <%= order.created_at.to_date %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%#= image_tag @order.product.photo_url, width: '100%' %></div>
    <div class="col">
      <h2 id="ty-header">Thank you!</h2>
        <p></p>
        <h3 id="order-num">Your order number is #<%= @order.id %> <p></p><small><span class="badge badge-primary"><%= @order.state %></span></small></h3>
     <p></p>
      <div class="order-list">
        <ul class="list-unstyled">
          <li><strong>Order date:</strong> <%= @order.created_at.to_date %></li>
          <li><strong>Purchased Item:</strong> <%= @order.product.name %></li>
          <li>Product SKU: <%= @order.product_sku %></li>
          <p></p>
          <li><strong>Order Total:</strong> <%= humanized_money_with_symbol @order.amount %></li>
        </ul>
      </div>
     <p></p>
      <p class="p-orders">Estimated delivery in <strong>2 business days</strong></p>
      <div class ="btn-orders">
        <%= link_to "Return to Dashboard", dashboard_path, class: "btn-new-index" %>
    </div>
    </div>
  </div>
</div>