config/routes.rb
Rails.application.routes.draw do

  # Authentication, Authorization
  devise_for :users

  # Forum
  mount SimpleDiscussion::Engine => "/forum"

  # Pages
  root to: 'pages#home'
  get '/info', to: 'pages#info', as: 'info'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  # Training
  resources :smell_programs, only: [:show, :index, :new, :create] do
    resources :smell_entries, only: [:new, :create] do
      collection do
        get :countdown
      end
    end
  end

  # Shop
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  resources :products, only: [:index, :show]
  resources :orders, only: [:index, :create] do
    resources :payments, only: :new
    member do
      get :success
    end
  end
end

app/views/pages/_progress_carousel.html.erb
<!-- Progress A,  Carousel -->
<div class="container-progress tiles">
  <div class="current-training">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= link_to smell_program_path(@active_trainings[0]), class: "link_tile" do %>
          <%= render "training_progress", locals: {format: 'carousel', training_id: 1, training: @active_trainings[0]}  %>
          <% end %>
        </div>
        <div class="carousel-item">
          <%= link_to smell_program_path(@active_trainings[1]), class: "link_tile" do %>
          <%= render "training_progress", locals: {format: 'carousel', training_id: 2, training: @active_trainings[1]}  %>
          <% end %>
        </div>
        <div class="carousel-item">
          <%= link_to smell_program_path(@active_trainings[2]), class: "link_tile" do %>
          <%= render "training_progress", locals: {format: 'carousel', training_id: 3, training: @active_trainings[2]}  %>
          <% end %>
        </div>
        <div class="carousel-item">
          <%= link_to smell_program_path(@active_trainings[3]), class: "link_tile" do %>
          <%= render "training_progress", locals: {format: 'carousel', training_id: 4, training: @active_trainings[3]}  %>
          <% end %>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>



<!-- Completed Traiings -->
<% if @completed_trainings.present? %>
<div class="mt-4">
  <h3>Completed Training</h3>
</div>
<div class="container-completed">
  <div class="completed-training">
    <div class="d-flex flex-column">
    <% @completed_trainings.each do |completed_training| %>
      <%= link_to(smell_program_path(completed_training)) do %>
        <%= render "training_progress", locals: {format: "band", training: completed_training}  %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/pages/_sliding_card.html.erb
  <% training = current_user.smell_programs.find( locals[:training_id] ) %>
  <div class="card">
    <%#= link_to smell_program_path(training, class: "link_tile") do %>
    <%= link_to dashboard_path(class: "link_tile") do %>
      <div class="training-card">
        <div class="d-flex flex-column justify-content-between">
          <h3 class="card-title p-0 m-0"><%= training.scent.name.capitalize %></h3>
          <div class="d-flex flex-column justify-content-end flex-grow-1">
            <div class="d-flex justify-content-start align-items-baseline">
              <p class="number mr-1 my-0 ml-0"><%= training.smell_entries.count %></p>
              <p class="label my-0 ml-0">tries</p>
            </div>
            <div class="d-flex justify-content-start align-items-baseline">
              <p class="number my-0 ml-0 mr-0"><%= training.progress %></p>
              <p class="percentage mr-1 my-0 ml-0">%</p>
              <p class="label my-0 ml-0">recovered</p>
            </div>
          </div>
        </div>
      <% if training.scent.photo.key %>
        <div class="card-image-container" style="background-image: linear-gradient(180deg, rgba(0,0,0,0.0), rgba(0,0,0,0.0)) , url('<%= cl_image_path training.scent.photo.key, class: "card-image" %>')">
        </div>
      <% end %>
     </div>
    <% end %>
  </div>

app/views/pages/_training_4x4_tiles.html.erb
<!-- Progress A, Start Training -->
<div class="container-progress tiles">
  <div class="current-training">
    <div class="flex-tiles">
      <%= link_to smell_program_path(@active_trainings[0]), class: "link_tile" do %>
        <%= render "training_progress", locals: {format: 'tile', side: "left", stack:"top", training_id: 1, training: @active_trainings[0]}  %>
      <% end %>
      <%= link_to smell_program_path(@active_trainings[1]), class: "link_tile" do %>
        <%= render "training_progress", locals: {format: 'tile', side: "right", stack:"top", training_id: 2, training: @active_trainings[1]} %>
      <% end %>
    </div>
    <div class="flex-tiles">
      <%= link_to smell_program_path(@active_trainings[2]), class: "link_tile" do %>
        <%= render "training_progress", locals: {format: 'tile', side: "left", stack: "bottom", training_id: 3, training: @active_trainings[2]}  %>
      <% end %>
      <%= link_to smell_program_path(@active_trainings[3]), class: "link_tile" do %>
        <%= render "training_progress", locals: {format: 'tile', side: "right", stack: "bottom", training_id: 4, training: @active_trainings[3]}%>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_training_progress.html.erb
 <% if locals[:format] == 'tile' %>
  <!-- Training / 4 x 4 tiles -->
  <div class="training-tile <%= "#{locals[:side]} #{locals[:stack]}" %>" style="background-image: linear-gradient(180deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.15) 50%) , url('<%= cl_image_path locals[:training].scent.photo.key, height: 300, crop: :fill %>')">
  <div class="program-info d-flex justify-content-between mb-0">
    <div><h3 class="program-title mb-0"><%= locals[:training].scent.name.capitalize %></h3></div>
    <div class="nr-entries"><p><%= locals[:training].smell_entries.length %></p></div>
  </div>
  <div class="chart mt-3">
    <%= render "ts_block_progress", locals: {training: locals[:training], scale_height: 5, width: 132}  %>
  </div>
  </div>

 <% elsif locals[:format] == 'carousel' %>
   <div class="training-carousel" style="background-image: linear-gradient(180deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.15) 50%) , url('<%= cl_image_path locals[:training].scent.photo.key, height: 300, crop: :fill %>')">
    <div class="program-info d-flex justify-content-between mb-0">
      <div><h3 class="program-title mb-0"><%= locals[:training].scent.name.capitalize %></h3></div>
      <div class="nr-entries"><p><%= locals[:training].smell_entries.length %></p></div>
    </div>
    <div class="chart mt-3 d-flex justify-content-center">
      <%= render "ts_block_progress", locals: {training: locals[:training], scale_height: 7, width: 200}  %>
    </div>
   </div>

<% elsif locals[:format] == 'band' %>
  <!-- bands tiles -->
  <div class="completed-tile" style="background-image: linear-gradient(180deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.1) 40%), url('<%= cl_image_path locals[:training].scent.photo.key, height: 300, crop: :fill %>')">
    <div class="d-flex justify-content-between align-items-center px-3 py-1" style="align-items: baseline;">
      <div><h3 class="program-title mb-0"><%= locals[:training].scent.name.capitalize %></h3></div>
        <div class="mt-3">
          <%= render "ts_block_progress", locals: {training: locals[:training], scale_height: 5, width: 200}  %>
        </div>
      <!-- <div class="nr-entries"><p><%#= locals[:training].smell_entries.length %></p></div> -->
    </div>
  </div>
<% end %>

app/views/pages/_ts_block_progress.html.erb
<div class="d-flex flex-column justify-content-center">
  <div>
    <div class="d-flex justify-content-start align-items-end dashboard-tile-data">
      <% locals[:training].smell_entries.each do |entry| %>
        <% if entry.strength_rating >= 4 %>
          <div class="db-strength-data strength-good" style="height:<%= entry.strength_rating * locals[:scale_height] %>px; width: <%= locals[:training].ts_block_width(locals[:width]) %>px;"></div>
        <% else %>
          <div class="db-strength-data" style="height:<%= entry.strength_rating * locals[:scale_height] %>px; width: <%= locals[:training].ts_block_width(locals[:width]) %>px;"></div>
        <% end %>
      <% end %>
    </div>
    <div class="d-flex justify-content-start align-items-start dashboard-tile-data">
      <% locals[:training].smell_entries.each do |entry| %>
        <% if entry.accuracy_rating >= 4 %>
          <div class="db-accuracy-data accuracy-good" style="height:<%= entry.accuracy_rating * locals[:scale_height] %>px; width: <%= locals[:training].ts_block_width(locals[:width]) %>px;"></div>
        <% else %>
          <div class="db-accuracy-data" style="height:<%= entry.accuracy_rating * locals[:scale_height] %>px; width: <%= locals[:training].ts_block_width(locals[:width]) %>px;"></div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<!--  personal Greeting -->
<!-- <div class="container dashboard">
  <div id="greeting">
    <p><%#= @greeting %>, <strong><%#= current_user.first_name %></strong>!</p>
  </div>
</div> -->


<!-- Section Title -->
<div class="w-100" style="background-image: linear-gradient(180deg, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0.0) 30%);">
  <div class="container">
    <div class="section-container">
      <p class="section-category">TRAINING</p>
      <h1 class="section-title">Unrecovered scent</h1>
    </div>
  </div>
</div>


<!-- Slider active-->
<div class="scrolling-wrapper" style="padding-top:35px">
  <% @smell_programs.current.each do |program| %>
  <%= render "sliding_card", locals: {training_id: program.id}  %>
  <% end %>
</div>


<!-- Buttons -->
<div class="d-flex justify-content-center" id="dash_board_btn_container">
    <!-- Start Training / Train again -->
    <% if @smell_programs.active.present? %>
      <div>
        <%= link_to "Start Training", countdown_smell_program_smell_entries_path(@smell_programs.active[0]), class: "btn-main padding-15-40 #{@button_width_css_class}" %>
      </div>
    <% elsif @smell_programs.current.present? %>
      <div>
        <%= link_to "Train again", dashboard_path(reset: true), class: "btn-main padding-15-40 #{@button_width_css_class}" %>
      </div>
    <% else %>
      <div>
        <%= link_to "You have recovered all scents!", dashboard_path(), class: "btn-main padding-15-40 #{@button_width_css_class}" %>
      </div>
    <% end %>

    <!-- option: Replace Programs  -->
    <% if @smell_programs.current.sufficently_trained.present? %>
      <% if current_user.remaining_scents.present? %>
        <% button_name = "New Scent" %>
      <% else %>
        <% button_name = "Remove Scents" %>
      <% end %>
      <div>
        <%= link_to button_name, dashboard_path(replace_trainings: true),
            class: "btn-inverse padding-15-40 #{@button_width_css_class}" %>
      </div>
    <% end %>
</div>


<!-- Section Title -->
<div class="container">
  <div class="section-container">
    <p class="section-category">TRAINING</p>
    <h1 class="section-title">Recovered scent</h1>
  </div>
</div>


<!-- Slider completed -->
<div class="scrolling-wrapper">
  <% @smell_programs.completed.each do |program| %>
  <%= render "sliding_card", locals: {training_id: program.id}  %>
  <% end %>
</div>


<!-- Quotes -->
<div class="container">
  <div class="quote-container d-flex justify-content-end">
    <div class= "quote-block">
      <blockquote>
        <p><%= @quote.text %></p>
        <cite>- <%= @quote.author %></cite>
      </blockquote>
    </div>
    <div class="quotation-mark">
    <svg width="72" height="71" viewBox="0 0 72 71" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" clip-rule="evenodd" d="M14.2433 62.8084C10.6697 62.2342 7.47043 60.2638 5.34949 57.3308C3.22855 54.3977 2.35961 50.7423 2.93384 47.1686C3.73116 42.2066 10.7478 27.2065 23.9865 2.17247L30.7238 3.25504L18.5736 35.8591C22.1473 36.4333 25.3465 38.4037 27.4675 41.3367C29.5884 44.2697 30.4574 47.9252 29.8831 51.4989C29.3089 55.0726 27.3385 58.2718 24.4055 60.3927C21.4725 62.5137 17.817 63.3826 14.2433 62.8084ZM47.93 68.2212C44.3563 67.647 41.1571 65.6766 39.0361 62.7436C36.9152 59.8106 36.0462 56.1551 36.6205 52.5814C37.4178 47.6194 44.4344 32.6194 57.6731 7.58532L64.4104 8.66789L52.2603 41.2719C55.834 41.8462 59.0332 43.8165 61.1541 46.7496C63.2751 49.6826 64.144 53.338 63.5698 56.9117C62.9955 60.4854 61.0252 63.6846 58.0921 65.8056C55.1591 67.9265 51.5037 68.7955 47.93 68.2212Z" fill="#E6DCD5"/>
    </svg>
    </div>
</div>
</div>

app/views/pages/home.html.erb
<div class="landing-container d-flex justify-content-center flex-column">

	<!-- title / description -->
  <div class="landing-details">
    <h2>Anosmiatherapy</h2>
     <hr class="d-solid">
     <div id="landing-desc">
     	<div>
      	<p class="text-desc">/aˈnäzmēə, aˈnäsmēə/</p>
      </div>
      <div>
        <p class="text-desc">/ˈTHerəpē/</p>
      </div>
    </div>
  </div>

  <!-- Image -->
  <div id="home-img"><%= image_tag "dashboard_image.png" %></div>
  <div class="landing-desc">
    <p class="text-desc-p">A smell training to help regain back your sense of smell</p>
  </div>

	<!-- Login , Sign in Buttons -->
  <div class="landing-btn btn-2">
  <% if user_signed_in? %>
    <%= link_to "Dashboard", dashboard_path,  class: "btn-main" %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete,  class: "btn-home-sign" %>
  <% else %>
    <%= link_to "Log In", new_user_session_path,  class: "btn-home-login" %>
    <%= link_to "Sign Up", new_user_registration_path,  class: "btn-home-sign" %>
  <% end %>
  </div>
</div>

app/views/pages/info.html.erb
<div class="container">
  <p class="section-category" id="section-title-info">About Us</p>
  <h2 id="info-header">Info</h2>
<div class="info-details">
    <h4>Smell training is a supportive technique for people who have suffered smell loss.</h4>
      <p class="info-text-1">
        It has been demonstrated in over a dozen scientific studies to be of benefit for people who have lost their sense of smell after a virus or injury. It used to be thought that it was only for people who had some natural recovery already and so could experience some smell messages. Now we know that if people start training immediately after the virus has cleared or the injury has taken place, they can improve their chances of smell recovery. This goes for post-viral and head injury patients.
      </p>
      <p></p>
    <h4>Think of it as physiotherapy for your nose. Smell training is not a cure, but a way of amplifying your recovery.</h4>
      <p></p>
      <p class="info-text-2">Every time you do it, you are stimulating the olfactory nerves that help you smell. And this is what encourages them to heal. As Nancy Rawson, cell biologist at the Monell Chemical Senses Center says “Smell training is not a far-fetched notion. It is based on years of learning how the olfactory and nervous systems work, and specifically, how nerve cells — and especially olfactory nerve cells — are generated or maintained.</p>
      <p></p>
      <p class="info-text-3">
        Through a specifically designed personal smell training course, the <i>Anosmiatherapy</i> app can help give back the ability to smell. Think of it as physiotherapy for your nose.
      </p>
</div>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <p>
  <%= current_user.first_name %>
  </p>
  <p>
  <%= current_user.last_name %>
  </p>
  <p>
  <%= current_user.email %>
  </p>
  <%= cl_image_tag current_user.avatar.key %>
</div>

app/views/pages/test.html.erb
<!-- countdown -->

<%= image_tag('dashboard_image.png', size: "100x100", alt: "dashboard_image", id: "#dashboard_image ") %>