config/routes.rb
Rails.application.routes.draw do

  # Authentication, Authorization
  devise_for :users

  # Forum
  mount SimpleDiscussion::Engine => "/forum"

  # Pages
  root to: 'pages#home'
  get '/info', to: 'pages#info', as: 'info'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  # Training
  resources :smell_programs, only: [:show, :index, :new, :create] do
    resources :smell_entries, only: [:new, :create] do
      collection do
        get :countdown
      end
    end
  end

  # Shop
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  resources :products, only: [:index, :show]
  resources :orders, only: [:index, :create] do
    resources :payments, only: :new
    member do
      get :success
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_type

  monetize :price_cents

  has_one_attached :photo
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @products = Product.all.sort_by(&:order)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/views/products/index.html.erb
<div class="container">
  <p class="section-category" id="section-title">PRODUCT</p>
  <h2 id="shop-header">Shop</h2>
  <div class="shop-cards">
    <% @products.each do |product| %>
        <div class="card-shop">
          <!-- <div class="card-title"> -->
            <%= link_to product_path(product) do %>
              <%= cl_image_tag product.photo.key, class: "card-img-bottom" %>
            <div class="product-details">
              <h5 class="h5-product"><%= product.name %></h5>
              <p id="product-price"><%= humanized_money_with_symbol(product.price) %></p>
            </div>
            <% end %>
          <!-- </div> -->
        </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container py-3">
  <div class="row">
    <!-- <div class="col-sm-12 col-md-6"> -->
    <div class="p-image">
      <%= cl_image_tag(@product.photo.key, width: '100%') %>
    </div>
    <!-- <div class="col-sm-12 col-md-6"> -->
    <div class="shop-info">
      <div class="d-flex justify-content-between align-items-center">
        <h2 id="show-header"><%= @product.name %></h2>
        <h3 class="m-0"><%= humanized_money_with_symbol(@product.price) %></h3>
      </div>
      <div class="show-text">
        <%= simple_format(@product.description, class: "product-desc") %>
      </div>
        <%= form_tag orders_path do %>
        <%= hidden_field_tag 'product_id', @product.id %>
    <div class="show-button">
      <%= submit_tag 'Purchase', class: 'btn-new-show' %>
    </div>
      <% end %>
    </div>
  </div>
</div>